### ISSUE TITLE
REPL says to visit a site which doesn't exist

### ISSUE THREAD

**Issue by Zireael07** [thekaigonzalez/salmon#2]
https://thekaigonzalez.github.io/slisp doesn't exist.

Also: FAQ doesn't mention if it's interpreted or compiled?

**Comment by thekaigonzalez** [comment]
Hello! Thanks for submitting an issue! I noticed this yesterday and I'm working on a fix right now.

And as for the FAQ: SLisp is interpreted.

**Comment by thekaigonzalez** [comment]
This issue has been fixed! Let me know if you have any other issues or concerns.
